/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    topics: Topic;
    testimonials: Testimonial;
    partners: Partner;
    cases: Case;
    'glossary-terms': GlossaryTerm;
    jobs: Job;
    pages: Page;
    posts: Post;
    resources: Resource;
    'specialist-roles': SpecialistRole;
    webinars: Webinar;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'specialist-roles': SpecialistRolesSelect<false> | SpecialistRolesSelect<true>;
    webinars: WebinarsSelect<false> | WebinarsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pt' | 'en') | ('pt' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'pt' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Who can access the panel. Only admins manage users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors publish content. Admins also change navigation, footer, the AI and users.
   */
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen reader users. Required.
   */
  alt: string;
  caption?: string | null;
  /**
   * Image source or authorship, when applicable.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Topics used to filter cases, posts and resources. Controlled vocabulary: prefer reusing over creating.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  name: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  description?: string | null;
  /**
   * Check to show this topic as a category button on listings.
   */
  showInFilter?: boolean | null;
  /**
   * Lower comes first.
   */
  filterOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client testimonials. Shown on the home page and inside cases.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  label?: string | null;
  quote: string;
  /**
   * Not translated: proper noun.
   */
  company: string;
  /**
   * Optional. Without a name, the site shows role and company only.
   */
  authorName?: string | null;
  authorRole: string;
  /**
   * Optional. Only use a real, authorised photo — without one the site shows initials.
   */
  photo?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Technology partners. Shown in the menu, on the home page and on partner pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Not translated: proper noun.
   */
  name: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  /**
   * Prefer SVG. The repository already has intact partner SVGs.
   */
  logo: number | Media;
  logoScale?: ('sm' | 'md' | 'lg') | null;
  /**
   * One sentence, used in the menu.
   */
  description: string;
  /**
   * E.g. Premier Partner.
   */
  tier?: string | null;
  featured?: boolean | null;
  /**
   * Without this, the partner appears in the menu but is not a link.
   */
  hasPage?: boolean | null;
  order?: number | null;
  /**
   * Optional. When empty, the site falls back to the page title and summary.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Up to 160 characters — Google truncates the rest.
     */
    metaDescription?: string | null;
    /**
     * Shown when shared on LinkedIn and WhatsApp. Falls back to the cover image.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Success stories. Drafts are not visible on the site — publish only when complete.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  title: string;
  /**
   * E.g. Banco ABC.
   */
  client: string;
  /**
   * Up to 220 characters. Used on the listing card and as the search description.
   */
  summary: string;
  /**
   * Line under the title on the case page. Falls back to the summary.
   */
  heroSubtitle?: string | null;
  heroImage: number | Media;
  /**
   * E.g. "51x faster". Shown over the card image.
   */
  impact?: string | null;
  challenges?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutClient?: string | null;
  /**
   * Used by the listing filter. At least one.
   */
  topics: (number | Topic)[];
  /**
   * Not translated: product names.
   */
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  partners?: (number | Partner)[] | null;
  /**
   * The same testimonial can appear here and on the home page.
   */
  testimonial?: (number | null) | Testimonial;
  clientLogo?: (number | null) | Media;
  /**
   * Optional. When empty, the site falls back to the page title and summary.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Up to 160 characters — Google truncates the rest.
     */
    metaDescription?: string | null;
    /**
     * Shown when shared on LinkedIn and WhatsApp. Falls back to the cover image.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  /**
   * Appears in the home carousel and the insights hub.
   */
  featured?: boolean | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Glossary terms, grouped by letter on /glossary.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  term: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  /**
   * A short explanation, for a non-technical reader.
   */
  definition: string;
  category: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Open roles. Unpublish when a role closes; do not delete, so the link keeps working.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  area: string;
  locationType: 'remote' | 'hybrid' | 'onsite';
  location?: string | null;
  summary: string;
  /**
   * Responsibilities, requirements and nice-to-haves. Publish only once filled in.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  /**
   * Optional. When empty, the site falls back to the page title and summary.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Up to 160 characters — Google truncates the rest.
     */
    metaDescription?: string | null;
    /**
     * Shown when shared on LinkedIn and WhatsApp. Falls back to the cover image.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Pages assembled from blocks. Drag to reorder sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  layout: (
    | {
        badge?: string | null;
        chip?: string | null;
        title: string;
        /**
         * Slices of the title shown in blue. Each must appear in the title.
         */
        highlight?: string[] | null;
        description?: string | null;
        mediaMode?: ('none' | 'image' | 'marquee') | null;
        /**
         * With a single image only the first is used. In the marquee, all of them.
         */
        images?: (number | Media)[] | null;
        ctas?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pageHero';
      }
    | {
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stickyPageNav';
      }
    | {
        source?: ('siteSettings' | 'custom') | null;
        customItems?:
          | {
              value: number;
              suffix?: string | null;
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsGrid';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        ctas?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        imagePosition?: ('left' | 'right' | 'none') | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richTextSection';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        columns?: ('2' | '3' | '4') | null;
        variant?: ('compact' | 'card') | null;
        headerWidth?: ('full' | 'narrow') | null;
        items: {
          icon:
            | 'sparkles'
            | 'target'
            | 'shield'
            | 'rocket'
            | 'users'
            | 'database'
            | 'cloud'
            | 'brain'
            | 'chart'
            | 'lock'
            | 'workflow'
            | 'award';
          title: string;
          /**
           * Left empty, the card renders compact and centred.
           */
          description?: string | null;
          id?: string | null;
        }[];
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'iconCardGrid';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        items: {
          icon:
            | 'sparkles'
            | 'target'
            | 'shield'
            | 'rocket'
            | 'users'
            | 'database'
            | 'cloud'
            | 'brain'
            | 'chart'
            | 'lock'
            | 'workflow'
            | 'award';
          glowColor?: ('blue' | 'orange') | null;
          title: string;
          description: string;
          id?: string | null;
        }[];
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'valueCards';
      }
    | {
        title?: string | null;
        partners: (number | Partner)[];
        /**
         * They gain colour on hover.
         */
        grayscale?: boolean | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'partnerShowcase';
      }
    | {
        title?: string | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'sealsBanner';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        /**
         * Numbering follows the order. Drag to reorder.
         */
        steps: {
          title: string;
          description: string;
          id?: string | null;
        }[];
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'processSteps';
      }
    | {
        title: string;
        subtitle?: string | null;
        /**
         * Phone, e-mail, address and socials beside the form.
         */
        showContactCard?: boolean | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaContact';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        emptyText?: string | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'jobsList';
      }
    | {
        title: string;
        highlight?: string | null;
        description?: string | null;
        cta?: {
          label?: string | null;
          href?: string | null;
        };
        variant?: ('primary' | 'subtle') | null;
        /**
         * When filled, the block joins the page side nav. E.g. who-we-are.
         */
        anchor?: string | null;
        /**
         * Empty falls back to the section title.
         */
        navLabel?: string | null;
        borda?: ('nenhuma' | 'topo' | 'ambas') | null;
        theme?: ('surface-1' | 'surface-2') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ctaBanner';
      }
  )[];
  /**
   * Optional. When empty, the site falls back to the page title and summary.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Up to 160 characters — Google truncates the rest.
     */
    metaDescription?: string | null;
    /**
     * Shown when shared on LinkedIn and WhatsApp. Falls back to the cover image.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Blog posts. Publish only once the body is written.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  /**
   * Up to 220 characters. Used on the card and as the search description.
   */
  description: string;
  coverImage: number | Media;
  /**
   * The article. Keep it as a draft while this is empty.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  /**
   * Optional. When empty, the site falls back to the page title and summary.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Up to 160 characters — Google truncates the rest.
     */
    metaDescription?: string | null;
    /**
     * Shown when shared on LinkedIn and WhatsApp. Falls back to the cover image.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Reports and ebooks. The kind decides which page lists the item.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  /**
   * Reports list on /reports; ebooks on /ebooks.
   */
  kind: 'report' | 'ebook';
  title: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  description: string;
  coverImage: number | Media;
  tags?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the ebook card.
   */
  pages?: number | null;
  /**
   * The material itself. Keep the item as a draft while this is empty.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  /**
   * Optional. When empty, the site falls back to the page title and summary.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Up to 160 characters — Google truncates the rest.
     */
    metaDescription?: string | null;
    /**
     * Shown when shared on LinkedIn and WhatsApp. Falls back to the cover image.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Consultant profiles shown on /consultores.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialist-roles".
 */
export interface SpecialistRole {
  id: number;
  role: string;
  /**
   * Two or three letters, on the card badge.
   */
  code: string;
  level: 'Senior' | 'Pleno' | 'Lead / Principal';
  icon:
    | 'sparkles'
    | 'target'
    | 'shield'
    | 'rocket'
    | 'users'
    | 'database'
    | 'cloud'
    | 'brain'
    | 'chart'
    | 'lock'
    | 'workflow'
    | 'award';
  gradient:
    | 'blue-cyan'
    | 'cyan-teal'
    | 'indigo-blue'
    | 'sky-indigo'
    | 'purple-indigo'
    | 'emerald-teal'
    | 'amber-orange'
    | 'blue-teal';
  description: string;
  /**
   * Technologies and topics. Also feed the page filter.
   */
  tags: {
    name: string;
    id?: string | null;
  }[];
  allocatedProjects?: number | null;
  allocatedPartners?: number | null;
  totalTeamSize?: number | null;
  certifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Webinars and online events. The video comes in as a YouTube or Vimeo link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars".
 */
export interface Webinar {
  id: number;
  title: string;
  /**
   * Final part of the URL. Generated from the title when left empty. Changing it after publishing breaks existing links.
   */
  slug: string;
  description: string;
  coverImage: number | Media;
  /**
   * As shown on the card. E.g. "Tomorrow, 3pm" or "May 10, 2026".
   */
  dateLabel: string;
  startsAt?: string | null;
  /**
   * Shown over the cover. E.g. 45:00.
   */
  duration?: string | null;
  /**
   * YouTube or Vimeo. Empty until the webinar has been recorded (D-11).
   */
  videoUrl?: string | null;
  tags?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower comes first.
   */
  order: number;
  /**
   * Optional. When empty, the site falls back to the page title and summary.
   */
  seo?: {
    /**
     * Up to ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Up to 160 characters — Google truncates the rest.
     */
    metaDescription?: string | null;
    /**
     * Shown when shared on LinkedIn and WhatsApp. Falls back to the cover image.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'specialist-roles';
        value: number | SpecialistRole;
      } | null)
    | ({
        relationTo: 'webinars';
        value: number | Webinar;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  showInFilter?: T;
  filterOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  label?: T;
  quote?: T;
  company?: T;
  authorName?: T;
  authorRole?: T;
  photo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  logoScale?: T;
  description?: T;
  tier?: T;
  featured?: T;
  hasPage?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  summary?: T;
  heroSubtitle?: T;
  heroImage?: T;
  impact?: T;
  challenges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  solution?: T;
  results?:
    | T
    | {
        text?: T;
        id?: T;
      };
  aboutClient?: T;
  topics?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  partners?: T;
  testimonial?: T;
  clientLogo?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  slug?: T;
  featured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  term?: T;
  slug?: T;
  definition?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  area?: T;
  locationType?: T;
  location?: T;
  summary?: T;
  body?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        pageHero?:
          | T
          | {
              badge?: T;
              chip?: T;
              title?: T;
              highlight?: T;
              description?: T;
              mediaMode?: T;
              images?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        stickyPageNav?:
          | T
          | {
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        statsGrid?:
          | T
          | {
              source?: T;
              customItems?:
                | T
                | {
                    value?: T;
                    suffix?: T;
                    label?: T;
                    id?: T;
                  };
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        richTextSection?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              body?: T;
              image?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              imagePosition?: T;
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        iconCardGrid?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              columns?: T;
              variant?: T;
              headerWidth?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        valueCards?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    glowColor?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        partnerShowcase?:
          | T
          | {
              title?: T;
              partners?: T;
              grayscale?: T;
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        sealsBanner?:
          | T
          | {
              title?: T;
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        ctaContact?:
          | T
          | {
              title?: T;
              subtitle?: T;
              showContactCard?: T;
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        jobsList?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              emptyText?: T;
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              title?: T;
              highlight?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              variant?: T;
              anchor?: T;
              navLabel?: T;
              borda?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  body?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  pages?: T;
  body?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specialist-roles_select".
 */
export interface SpecialistRolesSelect<T extends boolean = true> {
  role?: T;
  code?: T;
  level?: T;
  icon?: T;
  gradient?: T;
  description?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  allocatedProjects?: T;
  allocatedPartners?: T;
  totalTeamSize?: T;
  certifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webinars_select".
 */
export interface WebinarsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  dateLabel?: T;
  startsAt?: T;
  duration?: T;
  videoUrl?: T;
  tags?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Figures and seals used across pages. Changing here changes everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown on the home page and /sobre. One figure, whole site.
   */
  metrics?:
    | {
        value: number;
        /**
         * E.g. “+” or “x”. Empty for none.
         */
        suffix?: string | null;
        label: string;
        icon?:
          | (
              | 'sparkles'
              | 'target'
              | 'shield'
              | 'rocket'
              | 'users'
              | 'database'
              | 'cloud'
              | 'brain'
              | 'chart'
              | 'lock'
              | 'workflow'
              | 'award'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  seals?:
    | {
        name: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  foundedYear?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  metrics?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  seals?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  foundedYear?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}