import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_partners_blocks_bento_grid_items_footer_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up', 'arrow-up-right');
  CREATE TYPE "public"."enum_pages_blocks_bento_grid_items_footer_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up', 'arrow-up-right');
  CREATE TYPE "public"."enum__pages_v_blocks_bento_grid_items_footer_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up', 'arrow-up-right');
  CREATE TYPE "public"."enum_solutions_blocks_bento_grid_items_footer_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up', 'arrow-up-right');
  CREATE TYPE "public"."enum__solutions_v_blocks_bento_grid_items_footer_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up', 'arrow-up-right');
  ALTER TYPE "public"."enum_partners_blocks_icon_card_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_value_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_method_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_method_cards_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_bento_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_bento_grid_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_audience_split_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_audience_split_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_accordion_steps_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_partners_blocks_accordion_steps_image_badge_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_icon_card_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_value_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_method_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_method_cards_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_bento_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_bento_grid_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_audience_split_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_audience_split_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_accordion_steps_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_pages_blocks_accordion_steps_image_badge_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_icon_card_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_value_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_method_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_method_cards_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_bento_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_bento_grid_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_audience_split_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_audience_split_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_accordion_steps_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__pages_v_blocks_accordion_steps_image_badge_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_icon_card_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_value_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_method_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_method_cards_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_bento_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_bento_grid_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_audience_split_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_audience_split_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_accordion_steps_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_blocks_accordion_steps_image_badge_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_solutions_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_icon_card_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_value_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_method_cards_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_method_cards_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_bento_grid_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_bento_grid_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_audience_split_items_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_audience_split_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_accordion_steps_eyebrow_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_blocks_accordion_steps_image_badge_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum__solutions_v_version_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_specialist_roles_icon" ADD VALUE 'arrow-up-right';
  ALTER TYPE "public"."enum_site_settings_metrics_icon" ADD VALUE 'arrow-up-right';
  ALTER TABLE "partners_blocks_bento_grid_items" ADD COLUMN "footer_icon" "enum_partners_blocks_bento_grid_items_footer_icon";
  ALTER TABLE "pages_blocks_bento_grid_items" ADD COLUMN "footer_icon" "enum_pages_blocks_bento_grid_items_footer_icon";
  ALTER TABLE "_pages_v_blocks_bento_grid_items" ADD COLUMN "footer_icon" "enum__pages_v_blocks_bento_grid_items_footer_icon";
  ALTER TABLE "solutions_blocks_bento_grid_items" ADD COLUMN "footer_icon" "enum_solutions_blocks_bento_grid_items_footer_icon";
  ALTER TABLE "_solutions_v_blocks_bento_grid_items" ADD COLUMN "footer_icon" "enum__solutions_v_blocks_bento_grid_items_footer_icon";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "partners_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "partners_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_partners_blocks_icon_card_grid_items_icon";
  CREATE TYPE "public"."enum_partners_blocks_icon_card_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_partners_blocks_icon_card_grid_items_icon";
  ALTER TABLE "partners_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_partners_blocks_icon_card_grid_items_icon" USING "icon"::"public"."enum_partners_blocks_icon_card_grid_items_icon";
  ALTER TABLE "partners_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "partners_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_partners_blocks_value_cards_items_icon";
  CREATE TYPE "public"."enum_partners_blocks_value_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_partners_blocks_value_cards_items_icon";
  ALTER TABLE "partners_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_partners_blocks_value_cards_items_icon" USING "icon"::"public"."enum_partners_blocks_value_cards_items_icon";
  ALTER TABLE "partners_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "partners_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_partners_blocks_method_cards_items_icon";
  CREATE TYPE "public"."enum_partners_blocks_method_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_partners_blocks_method_cards_items_icon";
  ALTER TABLE "partners_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_partners_blocks_method_cards_items_icon" USING "icon"::"public"."enum_partners_blocks_method_cards_items_icon";
  ALTER TABLE "partners_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_partners_blocks_method_cards_eyebrow_icon";
  CREATE TYPE "public"."enum_partners_blocks_method_cards_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_partners_blocks_method_cards_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_partners_blocks_method_cards_eyebrow_icon";
  ALTER TABLE "partners_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_partners_blocks_bento_grid_items_icon";
  CREATE TYPE "public"."enum_partners_blocks_bento_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_partners_blocks_bento_grid_items_icon" USING "icon"::"public"."enum_partners_blocks_bento_grid_items_icon";
  ALTER TABLE "partners_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_partners_blocks_bento_grid_eyebrow_icon";
  CREATE TYPE "public"."enum_partners_blocks_bento_grid_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_partners_blocks_bento_grid_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_partners_blocks_bento_grid_eyebrow_icon";
  ALTER TABLE "partners_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "partners_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_partners_blocks_audience_split_items_icon";
  CREATE TYPE "public"."enum_partners_blocks_audience_split_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_partners_blocks_audience_split_items_icon";
  ALTER TABLE "partners_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_partners_blocks_audience_split_items_icon" USING "icon"::"public"."enum_partners_blocks_audience_split_items_icon";
  ALTER TABLE "partners_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_partners_blocks_audience_split_eyebrow_icon";
  CREATE TYPE "public"."enum_partners_blocks_audience_split_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_partners_blocks_audience_split_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_partners_blocks_audience_split_eyebrow_icon";
  ALTER TABLE "partners_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_partners_blocks_accordion_steps_eyebrow_icon";
  CREATE TYPE "public"."enum_partners_blocks_accordion_steps_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_partners_blocks_accordion_steps_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_partners_blocks_accordion_steps_eyebrow_icon";
  ALTER TABLE "partners_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_partners_blocks_accordion_steps_image_badge_icon";
  CREATE TYPE "public"."enum_partners_blocks_accordion_steps_image_badge_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "partners_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE "public"."enum_partners_blocks_accordion_steps_image_badge_icon" USING "image_badge_icon"::"public"."enum_partners_blocks_accordion_steps_image_badge_icon";
  ALTER TABLE "pages_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_pages_blocks_icon_card_grid_items_icon";
  CREATE TYPE "public"."enum_pages_blocks_icon_card_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_pages_blocks_icon_card_grid_items_icon";
  ALTER TABLE "pages_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_icon_card_grid_items_icon" USING "icon"::"public"."enum_pages_blocks_icon_card_grid_items_icon";
  ALTER TABLE "pages_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_pages_blocks_value_cards_items_icon";
  CREATE TYPE "public"."enum_pages_blocks_value_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_pages_blocks_value_cards_items_icon";
  ALTER TABLE "pages_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_value_cards_items_icon" USING "icon"::"public"."enum_pages_blocks_value_cards_items_icon";
  ALTER TABLE "pages_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_pages_blocks_method_cards_items_icon";
  CREATE TYPE "public"."enum_pages_blocks_method_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_pages_blocks_method_cards_items_icon";
  ALTER TABLE "pages_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_method_cards_items_icon" USING "icon"::"public"."enum_pages_blocks_method_cards_items_icon";
  ALTER TABLE "pages_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_method_cards_eyebrow_icon";
  CREATE TYPE "public"."enum_pages_blocks_method_cards_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_pages_blocks_method_cards_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_pages_blocks_method_cards_eyebrow_icon";
  ALTER TABLE "pages_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_bento_grid_items_icon";
  CREATE TYPE "public"."enum_pages_blocks_bento_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_bento_grid_items_icon" USING "icon"::"public"."enum_pages_blocks_bento_grid_items_icon";
  ALTER TABLE "pages_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_bento_grid_eyebrow_icon";
  CREATE TYPE "public"."enum_pages_blocks_bento_grid_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_pages_blocks_bento_grid_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_pages_blocks_bento_grid_eyebrow_icon";
  ALTER TABLE "pages_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_pages_blocks_audience_split_items_icon";
  CREATE TYPE "public"."enum_pages_blocks_audience_split_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_pages_blocks_audience_split_items_icon";
  ALTER TABLE "pages_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_audience_split_items_icon" USING "icon"::"public"."enum_pages_blocks_audience_split_items_icon";
  ALTER TABLE "pages_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_audience_split_eyebrow_icon";
  CREATE TYPE "public"."enum_pages_blocks_audience_split_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_pages_blocks_audience_split_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_pages_blocks_audience_split_eyebrow_icon";
  ALTER TABLE "pages_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_accordion_steps_eyebrow_icon";
  CREATE TYPE "public"."enum_pages_blocks_accordion_steps_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_pages_blocks_accordion_steps_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_pages_blocks_accordion_steps_eyebrow_icon";
  ALTER TABLE "pages_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_accordion_steps_image_badge_icon";
  CREATE TYPE "public"."enum_pages_blocks_accordion_steps_image_badge_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "pages_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE "public"."enum_pages_blocks_accordion_steps_image_badge_icon" USING "image_badge_icon"::"public"."enum_pages_blocks_accordion_steps_image_badge_icon";
  ALTER TABLE "_pages_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__pages_v_blocks_icon_card_grid_items_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_icon_card_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__pages_v_blocks_icon_card_grid_items_icon";
  ALTER TABLE "_pages_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_icon_card_grid_items_icon" USING "icon"::"public"."enum__pages_v_blocks_icon_card_grid_items_icon";
  ALTER TABLE "_pages_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__pages_v_blocks_value_cards_items_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_value_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__pages_v_blocks_value_cards_items_icon";
  ALTER TABLE "_pages_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_value_cards_items_icon" USING "icon"::"public"."enum__pages_v_blocks_value_cards_items_icon";
  ALTER TABLE "_pages_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__pages_v_blocks_method_cards_items_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_method_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__pages_v_blocks_method_cards_items_icon";
  ALTER TABLE "_pages_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_method_cards_items_icon" USING "icon"::"public"."enum__pages_v_blocks_method_cards_items_icon";
  ALTER TABLE "_pages_v_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_method_cards_eyebrow_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_method_cards_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__pages_v_blocks_method_cards_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__pages_v_blocks_method_cards_eyebrow_icon";
  ALTER TABLE "_pages_v_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_bento_grid_items_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_bento_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_bento_grid_items_icon" USING "icon"::"public"."enum__pages_v_blocks_bento_grid_items_icon";
  ALTER TABLE "_pages_v_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_bento_grid_eyebrow_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_bento_grid_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__pages_v_blocks_bento_grid_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__pages_v_blocks_bento_grid_eyebrow_icon";
  ALTER TABLE "_pages_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__pages_v_blocks_audience_split_items_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_audience_split_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__pages_v_blocks_audience_split_items_icon";
  ALTER TABLE "_pages_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_audience_split_items_icon" USING "icon"::"public"."enum__pages_v_blocks_audience_split_items_icon";
  ALTER TABLE "_pages_v_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_audience_split_eyebrow_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_audience_split_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__pages_v_blocks_audience_split_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__pages_v_blocks_audience_split_eyebrow_icon";
  ALTER TABLE "_pages_v_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_accordion_steps_eyebrow_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_accordion_steps_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__pages_v_blocks_accordion_steps_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__pages_v_blocks_accordion_steps_eyebrow_icon";
  ALTER TABLE "_pages_v_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_accordion_steps_image_badge_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_accordion_steps_image_badge_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_pages_v_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE "public"."enum__pages_v_blocks_accordion_steps_image_badge_icon" USING "image_badge_icon"::"public"."enum__pages_v_blocks_accordion_steps_image_badge_icon";
  ALTER TABLE "solutions_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "solutions_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_solutions_blocks_icon_card_grid_items_icon";
  CREATE TYPE "public"."enum_solutions_blocks_icon_card_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_solutions_blocks_icon_card_grid_items_icon";
  ALTER TABLE "solutions_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_solutions_blocks_icon_card_grid_items_icon" USING "icon"::"public"."enum_solutions_blocks_icon_card_grid_items_icon";
  ALTER TABLE "solutions_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "solutions_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_solutions_blocks_value_cards_items_icon";
  CREATE TYPE "public"."enum_solutions_blocks_value_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_solutions_blocks_value_cards_items_icon";
  ALTER TABLE "solutions_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_solutions_blocks_value_cards_items_icon" USING "icon"::"public"."enum_solutions_blocks_value_cards_items_icon";
  ALTER TABLE "solutions_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "solutions_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_solutions_blocks_method_cards_items_icon";
  CREATE TYPE "public"."enum_solutions_blocks_method_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_solutions_blocks_method_cards_items_icon";
  ALTER TABLE "solutions_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_solutions_blocks_method_cards_items_icon" USING "icon"::"public"."enum_solutions_blocks_method_cards_items_icon";
  ALTER TABLE "solutions_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_solutions_blocks_method_cards_eyebrow_icon";
  CREATE TYPE "public"."enum_solutions_blocks_method_cards_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_solutions_blocks_method_cards_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_solutions_blocks_method_cards_eyebrow_icon";
  ALTER TABLE "solutions_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_solutions_blocks_bento_grid_items_icon";
  CREATE TYPE "public"."enum_solutions_blocks_bento_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_solutions_blocks_bento_grid_items_icon" USING "icon"::"public"."enum_solutions_blocks_bento_grid_items_icon";
  ALTER TABLE "solutions_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_solutions_blocks_bento_grid_eyebrow_icon";
  CREATE TYPE "public"."enum_solutions_blocks_bento_grid_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_solutions_blocks_bento_grid_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_solutions_blocks_bento_grid_eyebrow_icon";
  ALTER TABLE "solutions_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "solutions_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_solutions_blocks_audience_split_items_icon";
  CREATE TYPE "public"."enum_solutions_blocks_audience_split_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_solutions_blocks_audience_split_items_icon";
  ALTER TABLE "solutions_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_solutions_blocks_audience_split_items_icon" USING "icon"::"public"."enum_solutions_blocks_audience_split_items_icon";
  ALTER TABLE "solutions_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_solutions_blocks_audience_split_eyebrow_icon";
  CREATE TYPE "public"."enum_solutions_blocks_audience_split_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_solutions_blocks_audience_split_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_solutions_blocks_audience_split_eyebrow_icon";
  ALTER TABLE "solutions_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_solutions_blocks_accordion_steps_eyebrow_icon";
  CREATE TYPE "public"."enum_solutions_blocks_accordion_steps_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum_solutions_blocks_accordion_steps_eyebrow_icon" USING "eyebrow_icon"::"public"."enum_solutions_blocks_accordion_steps_eyebrow_icon";
  ALTER TABLE "solutions_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_solutions_blocks_accordion_steps_image_badge_icon";
  CREATE TYPE "public"."enum_solutions_blocks_accordion_steps_image_badge_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE "public"."enum_solutions_blocks_accordion_steps_image_badge_icon" USING "image_badge_icon"::"public"."enum_solutions_blocks_accordion_steps_image_badge_icon";
  ALTER TABLE "solutions" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "solutions" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_solutions_icon";
  CREATE TYPE "public"."enum_solutions_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "solutions" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_solutions_icon";
  ALTER TABLE "solutions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_solutions_icon" USING "icon"::"public"."enum_solutions_icon";
  ALTER TABLE "_solutions_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_solutions_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__solutions_v_blocks_icon_card_grid_items_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_icon_card_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__solutions_v_blocks_icon_card_grid_items_icon";
  ALTER TABLE "_solutions_v_blocks_icon_card_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__solutions_v_blocks_icon_card_grid_items_icon" USING "icon"::"public"."enum__solutions_v_blocks_icon_card_grid_items_icon";
  ALTER TABLE "_solutions_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_solutions_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__solutions_v_blocks_value_cards_items_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_value_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__solutions_v_blocks_value_cards_items_icon";
  ALTER TABLE "_solutions_v_blocks_value_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__solutions_v_blocks_value_cards_items_icon" USING "icon"::"public"."enum__solutions_v_blocks_value_cards_items_icon";
  ALTER TABLE "_solutions_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_solutions_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__solutions_v_blocks_method_cards_items_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_method_cards_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__solutions_v_blocks_method_cards_items_icon";
  ALTER TABLE "_solutions_v_blocks_method_cards_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__solutions_v_blocks_method_cards_items_icon" USING "icon"::"public"."enum__solutions_v_blocks_method_cards_items_icon";
  ALTER TABLE "_solutions_v_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__solutions_v_blocks_method_cards_eyebrow_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_method_cards_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_method_cards" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__solutions_v_blocks_method_cards_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__solutions_v_blocks_method_cards_eyebrow_icon";
  ALTER TABLE "_solutions_v_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__solutions_v_blocks_bento_grid_items_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_bento_grid_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_bento_grid_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__solutions_v_blocks_bento_grid_items_icon" USING "icon"::"public"."enum__solutions_v_blocks_bento_grid_items_icon";
  ALTER TABLE "_solutions_v_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__solutions_v_blocks_bento_grid_eyebrow_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_bento_grid_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_bento_grid" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__solutions_v_blocks_bento_grid_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__solutions_v_blocks_bento_grid_eyebrow_icon";
  ALTER TABLE "_solutions_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "_solutions_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__solutions_v_blocks_audience_split_items_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_audience_split_items_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum__solutions_v_blocks_audience_split_items_icon";
  ALTER TABLE "_solutions_v_blocks_audience_split_items" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__solutions_v_blocks_audience_split_items_icon" USING "icon"::"public"."enum__solutions_v_blocks_audience_split_items_icon";
  ALTER TABLE "_solutions_v_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__solutions_v_blocks_audience_split_eyebrow_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_audience_split_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_audience_split" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__solutions_v_blocks_audience_split_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__solutions_v_blocks_audience_split_eyebrow_icon";
  ALTER TABLE "_solutions_v_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__solutions_v_blocks_accordion_steps_eyebrow_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_accordion_steps_eyebrow_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_accordion_steps" ALTER COLUMN "eyebrow_icon" SET DATA TYPE "public"."enum__solutions_v_blocks_accordion_steps_eyebrow_icon" USING "eyebrow_icon"::"public"."enum__solutions_v_blocks_accordion_steps_eyebrow_icon";
  ALTER TABLE "_solutions_v_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__solutions_v_blocks_accordion_steps_image_badge_icon";
  CREATE TYPE "public"."enum__solutions_v_blocks_accordion_steps_image_badge_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v_blocks_accordion_steps" ALTER COLUMN "image_badge_icon" SET DATA TYPE "public"."enum__solutions_v_blocks_accordion_steps_image_badge_icon" USING "image_badge_icon"::"public"."enum__solutions_v_blocks_accordion_steps_image_badge_icon";
  ALTER TABLE "_solutions_v" ALTER COLUMN "version_icon" SET DATA TYPE text;
  ALTER TABLE "_solutions_v" ALTER COLUMN "version_icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum__solutions_v_version_icon";
  CREATE TYPE "public"."enum__solutions_v_version_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "_solutions_v" ALTER COLUMN "version_icon" SET DEFAULT 'sparkles'::"public"."enum__solutions_v_version_icon";
  ALTER TABLE "_solutions_v" ALTER COLUMN "version_icon" SET DATA TYPE "public"."enum__solutions_v_version_icon" USING "version_icon"::"public"."enum__solutions_v_version_icon";
  ALTER TABLE "specialist_roles" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "specialist_roles" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_specialist_roles_icon";
  CREATE TYPE "public"."enum_specialist_roles_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "specialist_roles" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_specialist_roles_icon";
  ALTER TABLE "specialist_roles" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_specialist_roles_icon" USING "icon"::"public"."enum_specialist_roles_icon";
  ALTER TABLE "site_settings_metrics" ALTER COLUMN "icon" SET DATA TYPE text;
  ALTER TABLE "site_settings_metrics" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::text;
  DROP TYPE "public"."enum_site_settings_metrics_icon";
  CREATE TYPE "public"."enum_site_settings_metrics_icon" AS ENUM('sparkles', 'target', 'shield', 'rocket', 'users', 'database', 'cloud', 'brain', 'chart', 'lock', 'workflow', 'award', 'app', 'search', 'settings', 'zap', 'cpu', 'shield-check', 'trending-up');
  ALTER TABLE "site_settings_metrics" ALTER COLUMN "icon" SET DEFAULT 'sparkles'::"public"."enum_site_settings_metrics_icon";
  ALTER TABLE "site_settings_metrics" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_site_settings_metrics_icon" USING "icon"::"public"."enum_site_settings_metrics_icon";
  ALTER TABLE "partners_blocks_bento_grid_items" DROP COLUMN "footer_icon";
  ALTER TABLE "pages_blocks_bento_grid_items" DROP COLUMN "footer_icon";
  ALTER TABLE "_pages_v_blocks_bento_grid_items" DROP COLUMN "footer_icon";
  ALTER TABLE "solutions_blocks_bento_grid_items" DROP COLUMN "footer_icon";
  ALTER TABLE "_solutions_v_blocks_bento_grid_items" DROP COLUMN "footer_icon";
  DROP TYPE "public"."enum_partners_blocks_bento_grid_items_footer_icon";
  DROP TYPE "public"."enum_pages_blocks_bento_grid_items_footer_icon";
  DROP TYPE "public"."enum__pages_v_blocks_bento_grid_items_footer_icon";
  DROP TYPE "public"."enum_solutions_blocks_bento_grid_items_footer_icon";
  DROP TYPE "public"."enum__solutions_v_blocks_bento_grid_items_footer_icon";`)
}
